### ISSUE TITLE
Unicode characters in buffer names

### ISSUE THREAD

**Issue by de-vri-es** [de-vri-es/weechat-autosort#10]
```
11:36 autosort: Individual evaluation results:
11:36 autosort: core.weechat: ['0', '0', '', '1', '', '1', 'weechat', 'core.weechat']
11:36 autosort: python.capitaines: ['1', '0', 'python', '1', '', '0', 'capitaines', 'python.capitaines']
11:36 autosort: python.capitainetrain: ['1', '0', 'python', '1', '', '0', 'capitainetrain', 'python.capitainetrain']
11:36 autosort: python.trainline: ['1', '0', 'python', '1', '', '0', 'trainline', 'python.trainline']
11:36 python: stdout/stderr: Traceback (most recent call last):
11:36 python: stdout/stderr:   File "/home/name/.weechat/python/autosort.py", line 688, in on_autosort_command
11:36 python: stdout/stderr:     'swap':   command_helper_swap,
11:36 python: stdout/stderr:   File "/home/name/.weechat/python/autosort.py", line 572, in call_command
11:36 python: stdout/stderr:     return child(buffer, command, tail)
11:36 python: stdout/stderr:   File "/home/name/.weechat/python/autosort.py", line 414, in command_debug
11:36 python: stdout/stderr:     log('{0}: {1}'.format(fullname, result))
11:36 python: stdout/stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)
11:36 =!= python: error in function "on_autosort_command"
```

**Comment by de-vri-es** [comment]
Fixed in 3.3
