### ISSUE TITLE
Plugin fails to load: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by alem0lars** [de-vri-es/weechat-autosort#6]
When I try to load the plugin (using python3) I get the following error:

```
weechat     | python: loading script "/home/alem0lars/.weechat/python/autoload/autosort.py"
weechat     | python: registered script "autosort", version 2.7 (Automatically or manually keep your buffers sorted and grouped by server.)
weechat     | python: stdout/stderr: Traceback (most recent call last):
weechat     | python: stdout/stderr:   File "/home/alem0lars/.weechat/python/autoload/autosort.py", line 877, in <module>
weechat     | python: stdout/stderr:     on_config_changed()
weechat     | python: stdout/stderr:   File "/home/alem0lars/.weechat/python/autoload/autosort.py", line 691, in on_config_changed
weechat     | python: stdout/stderr:     on_buffers_changed()
weechat     | python: stdout/stderr:   File "/home/alem0lars/.weechat/python/autoload/autosort.py", line 675, in on_buffers_changed
weechat     | python: stdout/stderr:     buffers.sort(key=buffer_sort_key(config.rules))
weechat     | python: stdout/stderr:   File "/home/alem0lars/.weechat/python/autoload/autosort.py", line 450, in key
weechat     | python: stdout/stderr:     for word in preprocess(buffer[0].decode('utf-8'), config):
weechat     | python: stdout/stderr: AttributeError: 'str' object has no attribute 'decode'
weechat =!= | python: unable to parse file "/home/alem0lars/.weechat/python/autoload/autosort.py"
```

**Comment by de-vri-es** [comment]
Should be fixed now by #7. Thanks for the report and PR.
